vaultwarden:
  Image: 'vaultwarden/server:latest' 
  Service:
      port: 80
  PVC:
      storageClassName: nfs-csi
      capacity: 1Gi
  Ingress:
    Host: vault.thelmalouise.ddns.net
    prefix: ""
  Volumes:
        config:
          type: volumenClain
          mountPath: /data
        
  


